defaults:
  - hydra: default

checkpoint_path: "/mnt/newvolume/PushOdd_2Distractors_Dense/2025-11-11_15-13-23/logs/version_0/checkpoints/sold-steps=5100000-episode=102000-eval_episode_return=64.77089464293202.ckpt"  # Can be one checkpoint or a directory of checkpoints.
experiment: "PushOdd_2Distractors_Dense_ours"
eval_episodes: 5
seed: 42

env:
  _target_: envs.make_env
  suite: "mof"  # Should be "mof", "gym", or "dmcontrol".
  name: PushOdd_0to2Distractors_Dense-v1
  image_size: [ 64, 64 ]
  max_episode_steps: 50
  action_repeat: 2