defaults:
  - hydra: default
  - _self_

experiment: "Robosuite_pickplace_slotcon_data_autoenc"
save_format: "png"

num_train: 20_000  # Number of episodes in the 'train' split.
num_val: 2_000
num_test: 2_000

num_workers: 8

env:
  _target_: envs.make_env
  suite: robosuite   # Should be "mof", "gym", or "dmcontrol".
  name: PickPlace_birdview
  image_size: [ 224, 224 ]
  max_episode_steps: 25
  action_repeat: 2

