defaults:
  - autoencoder: savi  # Select the autoencoder architecture to train (cnn, savi)
  - callbacks: autoencoder
  - hydra: default
  - logger: tensorboard
  - trainer: gradient_clipping
  - _self_

checkpoint: ""
experiment: "robosuite_pickplace_savi"
seed: 42

dataset:
  _target_: datasets.image.load_image_dataset
  path: /mnt/newvolume/sold_autoenc_data/robosuit/Robosuite_pickplace_slotcon_data_autoenc
  data_dir: 2025-11-16_18-05-56
  num_workers: 8
  batch_size: 64
  sequence_length: 8

model:
  _target_: train_autoencoder.AutoencoderModule
  autoencoder: ${..autoencoder}

  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0001

  scheduler:
    scheduler:
      _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
      _partial_: True
      warmup_epochs: 10  # Number of warmup epochs.
      max_epochs: ${....trainer.max_epochs}
    extras:
      interval: "epoch"
